---
name: Zachary J.
surname: Beneduci
#position: "Research Technician"
address: "361 Mell St, Auburn University, AL 36849"
phone: +1 518 937 7585
www: zacharybeneduci.weebly.com
email: "beneduci.zachary@gmail.com"
#twitter: 
github: beneducizachary
#linkedin: 
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 414141
author: \textbf{Beneduci, Z. J.}
header-includes:
  - \usepackage{xesearch}
  - \SearchList{mbold}{\textbf{Beneduci}}{BeneduciBold}
  - \usepackage{enumitem}
  - \setlist[itemize,1]{label={}}
  - \usepackage{fancyhdr}
  - \fancyfoot[L]{\textcolor{gray}{\textit{Updated \today}}}
  - \pagestyle{fancy}
output: 
  vitae::moderncv:
    theme: banking
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r include=FALSE}
# Packages

library(vitae)
library(rorcid)
library(bibtex)
library(tidyverse)
library(glue)
library(scholar)
library(RefManageR)
library(rcrossref)
```

# Education

```{r education}
edu <- orcid_educations("0009-0001-9575-001X")$`0009-0001-9575-001X`$`affiliation-group`$summaries %>% 
  reduce(full_join) %>%
  as.data.frame() %>%
  mutate(GPA = c("4.0 GPA", "3.75 GPA"),
         country = "USA",
         startyear = `education-summary.start-date.year.value`,
         startmonth = `education-summary.start-date.month.value`,
         startday = `education-summary.start-date.day.value`,
         endyear = `education-summary.end-date.year.value`,
         endmonth = `education-summary.end-date.month.value`,
         endday = `education-summary.end-date.day.value`,
         startdate = paste(startyear, startmonth, startday, sep = "-"),
         enddate = paste(endyear, endmonth, endday, sep = "-")) %>%
  mutate(startdate = ymd(startdate),
         enddate = ymd(enddate)) %>%
  mutate(startmonth = month(startdate, label = T),
         endmonth = month(enddate, label = T))
edu %>%
  detailed_entries(
    with = glue("{`education-summary.role-title`}; {GPA}"),
    where = glue("{startmonth} {startyear} - {endmonth} {endyear}"),
    what = glue("{`education-summary.organization.name`}, {`education-summary.organization.address.city`}, {`education-summary.organization.address.region`}, {country}"))
```

# Employment

```{r employment}
manual <- read.csv("manualdata.csv")

manual %>%
  filter(Category == "employment") %>%
  detailed_entries(what = glue("{employer}, {city}, {state}, {country}"),
                   where = date,
                   with = title,
                   why = description,
                   .protect = FALSE)
```

```{r include=FALSE}
# Put here to count the publication number
DOI <- rorcid::orcid_citations("0009-0001-9575-001X")$ids %>%
  na.omit()
```

# Publications (`r summary(DOI)[1]`)

```{r publications}

## 2. Give a name for the output file:
OUTFILE <- "outfile.bib"

## 3. Run the followings:
baseurl <- "https://dx.doi.org/"
hdr <- "application/x-bibtex"
names(hdr) <- "Accept"

for (doi in DOI) {
    theurl <- paste0(baseurl, doi)
    URL <- url(theurl, headers = hdr)
    X <- try(scan(URL, "", sep = "\n"))
    close(URL)
    if (inherits(X, "try-error")) {
        cat("==>> Download failed for doi =", doi, "<<==\n")
        next
    }
    cat(X, sep = "\n", file = OUTFILE, append = TRUE)
    cat("\n", file = OUTFILE, append = TRUE)
} 

bibliography_entries("outfile.bib") %>%
  dplyr::arrange(dplyr::desc(issued)) %>%
  dplyr::mutate(
    author = {
      author_to_edit <- author
      for (j in seq_along(author_to_edit)) {
        for (i in seq_along(author_to_edit[[j]])) {
          if (author_to_edit[[j]][[i]]$family == "Beneduci") {
            author_to_edit[[j]][[i]]$family <- "BeneduciBold"
          }
        }
      }
      author_to_edit
    }
  )

```

```{r include=FALSE}
# Add this first so we can get the presentation count
# Need to format these as type "book' in Zotero.
pres.bib <- bibliography_entries("CV.bib") %>%
  filter(note == "presentation") %>%
  arrange(desc(issued), author$family) %>%
  dplyr::mutate(
    author = {
      author_to_edit <- author
      for (j in seq_along(author_to_edit)) {
        for (i in seq_along(author_to_edit[[j]])) {
          if (author_to_edit[[j]][[i]]$family == "Beneduci") {
            author_to_edit[[j]][[i]]$family <- "BeneduciBold"
          }
        }
      }
      author_to_edit
    }
  )
```

# Presentations (`r nrow(pres.bib)`)

```{r}
pres.bib1 <- pres.bib %>%
  filter(str_starts(id, "beneduci"))
```

## Presenter (`r nrow(pres.bib1)`)

```{r}
# Call the previous object
pres.bib1
```

```{r include=FALSE}
# Create the co-author object to count
pres.bib2 <- pres.bib %>%
  filter(!str_starts(id, "beneduci"))
```

## Co-author (`r nrow(pres.bib2)`)

```{r}
pres.bib2
```

# Awards

```{r}
manual %>%
  filter(Category == "award") %>%
  arrange(desc(date)) %>%
  detailed_entries(with = title,
                   where = date,
                   what = employer,
                   #when = 
                   why = description,
                   .protect = TRUE)
```

# Teaching
## Teaching Assitantships

```{r}
manual %>%
  filter(Category == "TA") %>%
  brief_entries(what = title,
                when = date,
                with = description)
```

# Outreach

## Non-refereed papers and blogs
```{r}
bibliography_entries("CV.bib") %>%
  filter(note == "article") %>%
  arrange(desc(issued))
```

## Talks

```{r}
bibliography_entries("CV.bib") %>%
  filter(note == "talk") %>%
  arrange(desc(issued))
```

## Other

```{r}
bibliography_entries("CV.bib") %>%
  filter(!note == "article",
         !note == "talk",
         !note == "presentation") %>%
  arrange(desc(note), desc(issued))
```

# Software Skills

ArcGIS Pro, Microsoft Office Suite, R statistical environment
